runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

handlers:
#models
  - url: /(.*\.h5)
    static_files: sudokuApp/static/trainedModels/\1
    upload: sudokuApp/trainedModels/(.*\.h5)
    application_readable: true

# image files
  - url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
    static_files: sudokuApp/static/siteImages/\1
    upload: sudokuApp/static/siteImages/(.*\.(bmp|gif|ico|jpeg|jpg|png))
    application_readable: true


# #this works!!!!!!!!!!!!!!!!!!! Which is odd because model is not in static folder
# #models
#   - url: /(.*\.h5)
#     static_files: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5
#     upload: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5
#     application_readable: true




# # image files
#   - url: /sudokuApp/trainedModels
#     static_dir: sudokuApp/trainedModels
#     application_readable: true

# #models
#   - url: /(.*\.h5)
#     static_files: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5
#     application_readable: true
#     upload: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5






# #models
#   - url: /(.*\.h5)
#     static_files: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5
#     application_readable: true
#     upload: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5

#   - url: (.*\.h5)
#     static_files: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5
#     application_readable: true
#     upload: sudokuApp/static/trainedModels/DigitRecogConvnetRev2.h5

#   - url: /.*
#     static_files: sudokuApp/static/\1
#     application_readable: true
#     upload: sudokuApp/static/.*





# - url: /(.*\.css)
#   mime_type: text/css
#   static_files: static/\1
#   upload: static/(.*\.css)

# - url: /(.*\.html)
#   mime_type: text/html
#   static_files: static/\1
#   upload: static/(.*\.html)

# - url: /(.*\.js)
#   mime_type: text/javascript
#   static_files: static/\1
#   upload: static/(.*\.js)

# - url: /(.*\.txt)
#   mime_type: text/plain
#   static_files: static/\1
#   upload: static/(.*\.txt)

# # index files
# - url: /(.+)/
#   static_files: static/\1/index.html
#   upload: static/(.+)/index.html

# test settings
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10
